module.exports = {
  FN: "FN",
  IF: "IF",
  EQ: "EQ",
  OR: "OR",
  AND: "AND",
  NOT: "NOT",
  DEF: "DEF",
  NULL: "NULL",
  BOOL: "BOOL",
  MEMBER: "MEMBER",
  NOT_EQ: "NOT_EQ",
  NUMBER: "NUMBER",
  STRING: "STRING",
  SYMBOL: "SYMBOL",
  VECTOR: "VECTOR",
  EXPORT: "EXPORT",
  DECLARE: "DECLARE",
  FN_CALL: "FN_CALL"
};
